#index:
#    path: /
#    controller: App\Controller\DefaultController::index

legacy:
  path: /{req}
  defaults: { _controller: 'App\Controller\Legacy\LegacyController::index' }
#  defaults: { _controller: 'App\Controller\Legacy\LegacyTransactionController::content' }
  requirements:
    req: ".*"