The week started with two teams atop their divisions and four teams trying to catch them. It ends with five of those teams tied for division titles and playoff spots. To help clarify the races, look for a breakdown of division title possibilities on Thursday.</p>

<p>In the Gold Division, the Crusaders gave away their one game lead, by losing to the Gallic Warriors, 30-0. This is the third straight week that the Gallic Warriors have been involved in a shutout. In the other division, the Bug Stompers also fell, to playoff contender Whiskey Tango. This ends the Bug Stompers' franchise record regular season winning streak and single season streak at 6 games.</p>

<p>With a chance to tie for the division lead, the Sacks on the Beach defeated the Lindbergh Baby Casserole for the third straight time, 66-19. In the final game involving playoff teams, the MeggaMen and the Werewolves played. The Werewolves shutout the MeggaMen, 34-0, for the second time this season (87-0 in head-to-head meetings). This marks the 5th shutout for the Werewolves this year and the 4th time the MeggaMen have been shutout (they avoided a 5th shutout in week 3, due to the 0-0 rule).</p>

<p>Finally, in a game with Toliet Bowl implications, the Rednecks also completed a season shutout sweep over the Norsemen, 15-0. This is the also the 4th time the Norsemen have been shutout this year and marks the 4th straight meeting of these teams that has ended with someone being blanked.</p>

<p><b>Player of the Week</b> - Ladainian Tomlinson (RB-SD) - SOB<br/>
<b>Defensive Player</b> - Jason Taylor (DL-MIA) - MM 
