This week featured battles atop both divisions. In the Burgandy Division, the Bug Stompers crushed the Werewolves, 84-35, to tie their franchise single season winning streak at 6 games. The Crusaders took control of the Gold Division by beating the MeggaMen for only the second time in 8 meetings, 65-53.</p>

<p>In other playoff contenting games, the Whiskey Tango eliminated the Gallic Warriors, 19-0. (If it wasn't alrady obvious, the Norsemen, Lindbergh Baby Casserole and Rednecks have also been eliminated from playoff contention). The Sacks on the Beach kept pace by downing the Norsemen 37-36, to spite a Sunday night comeback by the Norsemen that fizzled in the final drive of the game.</p>

<p>Finally, in a possible Toliet Bowl preview the Lindbergh Baby Casserole took on the Rednecks. In thier 8th attempt, they finally picked up thier 100th franchise victory. Becoming the fourth franchise to reach that point.</p>

<p><b>Player of the Week</b> - Kurt Warner (QB-ARZ) - BS<br/>
<b>Defensive Player</b> - Adrian Wilson (DB-ARZ) - WT 
