This week the Norsemen activated a player not on thier roster as well as a player on a bye. That costed them 4 points and $2. In spite of that, helped by both the Player of the Week (Santana Moss) and the Defensive Player of Week (Jared Allen), they manged to end their four game losing streak. Their 32-10 victory over the Lindbergh Baby Casserole is their fourth straight win over that team.</p>

<p>The Crusaders defeated the Gallic Warriors for the fifth time in six meetings, by a score of 4-1. That coupled with the Whiskey Tango's 24-26 loss to the Bug Stompers, puts the Crusaders in first place of the Gold Division all by themselves.</p>

<p>The top of the Burgandy Division remains the same, with the Werewolves sending the Rednecks to their fifth straight loss (53-2). The Sacks of the Beach defeated the MeggaMen, by the same 53-0 score that they did in last year's meeting of those teams.</p>

<p><b>Player of the Week</b> - Sanatana Moss (WR-WAS) - NOR<br/>
<b>Defensive Player</b> - Jared Allen (DL-KC) - NOR
