The Werewolves and the Sacks on the Beach both broke the old offensive points record, by a lot. By the end of the 4:00 games the Werewolves had 135 points, 10 more than the previous record. In the Sunday night game, the Sacks scored 67 points by double dipping with LT and his offensive line. This left them tied with the old record at 125. On Monday, Jason Elam picked up 14, pushing the Sacks pass the Werewolves to a new record of 139. Ladainian Tomlinson's 42 points is the 5th best by a running back (see the Player Records stats page, which now works. I'm still working on the Financial Status page though). It is also only the 12th time a player at any position has scored 40 or more and made LT the first player to do it more than once (Week 13 of 2002 he scored 46).</p>

<p>Needless to say, both the Sacks on the Beach and the Werewolves won their games comfortably. They defeated the Gallic Warriors and the Crusaders, respectivly, by scores of 105-39 and 102-63.</p>

<p>The MeggaMen managed to take advantage of the re-estatment of the 1-0 rule to pick up their first win of the season. It is also the first game they haven't been shutout, but they really were shutout, but it doesn't count as a shutout. (Still seems wierd to me.) Interesting fact here, 5 of the last 6 games the MeggaMen have played have been shutouts, one way or another. It is the 7th straight time the MeggaMen have defeated the Norsemen, tied for longest current streak in the league (LBC over Gallic Warriors).</p>

<p>The Bug Stompers pickup a 30-7 victory over the Rednecks. Their defense scored 53, led by defensive player of the week, Dwight Freeney's 15 pts. Finally, the Lindbergh Baby Casserole won their first game and gave the Whiskey Tango thier first defeat, 39-8.</p>

<p><b>Player of the Week</b> - Ladainian Tomlinson (RB-SD) - SOB<br/>
<b>Defensive Player</b> - Dwight Freeney (DL-IND) - BS
