<p>
In Week 4 action, the Sacks on the Beach regained a share of first place
with a 84-19 thrashing of the LBC.  This gets their all-time regular 
season record back up to .500 (36-36-2).  In the last 3 weeks they have 
outscored opponents 239-58.</p>

<p>For the first time since taking over ownership, Chris' Gallic Warriors
defeated the Norsemen.  This marks the franchises 60th all-time win.  With
an even longer streak broken, Warren picks up his first win over the 
Werewolves since 2000.  In fact, it's the first time his team has managed
to score points.  Sadly, this brings an admission, that Warren's team
may not suck.</p>

<p>In other games, the Crusaders kept pace with the Whiskey Tango, by taking
out the Rednecks 26-11.  And the MeggaMen downed the Bug Stompers 42-15.</p>

<p>
<b>Player of the Week</b> - Peyton Manning (QB-IND) - NOR<br/>
<b>Defensive Player</b> - Charles Grant (DL-NO) - WT<br/>
