The season starts out with the Crusaders reminding the Sacks on the Beach
who lost the Toliet Bowl.  Kerry Collins scores 19 points to advance the
Crusaders to a 28-14 victory.  Their first regular season victory over the
Sacks since 2001.</p>

<p>The Norsemen picked up right where they left off, winning their 9th straight
regular season game, tied for the third longest streak in league history.  They
defeat the Bug Stompers, 21-4.  Making Ayrik the fifth straight new owner to
lose his first game in the league.</p>

<p>The Werewolves win on opening day for the 5th straight year, to advance their
opening day record to 11-3 all-time.  The 16-0 victory over the Lindbergh
Baby Casserole is the 99th regular season win in fanchise history.</p>

<p>Anchored by the Player of the Week, Larry Fitzgerald, and a crushing defense,
the Rednecks shutout the Gallic Warriors for the second straight time, 4-0.
In the final game, the defending champions fall to the the Whiskey Tango, 11-0.
That ends the MeggaMen's 6 game non-losing streak and dethrones the MeggaMen
as the team with the best all-time record.  (MeggaMen 41-31-4 .566 vs Norsemen
109-81-2 .573).</p>

<p align="center">
<b>Player of the Week -</b> Larry Fitzgerald (WR-ARI) - RED<br/>
<b>Defensive Player -</b> Jason Taylor (DL-MIA) - MM<br/>

