In the final bye week, the Norsemen, Crusaders and Whiskey Tango all activate players on a byes. This weeks games leaves the playoff race tight as can be. Both division have two teams at 7-3 and one at 6-4. And in both cases the 7-3 teams play each other next week.</p>

<p>In the first game, the Whiskey Tango catch up to the pack by defeating the Crusaders, 40-31. This ties at all-time regular season series between these two teams and they have alternated wins over their last 7 meetings. That game allowed the MeggaMen to move into a tie for the division lead by beating the Rednecks in a rematch of last year's Championship, 25-13.</p>

<p>The Burgandy division began the week in a three way tie. The Bug Stompers and Sacks on the Beach met with the Bug Stompers winning a franchise regular season record 5th straight game. This is the sixth straight time the Bug Stompers have defeated the Sacks, 44-29. To remain tied for first place the Werewolves played the Norsemen for the 30th time. Shutting them out 24-0, they have beat the Norsemen 4 of the last 5 meetings.</p>

<p>In the final game of the week, the Lindbergh Baby Casserole extended their franchise record losing streak to 7 games, now tied for the 4th longest in league history. This is only the 3rd time the Gallic Warrior franchise has defeated the LBC, in 21 meetings.</p>

<p><b>Player of the Week</b> - Mike Peterson (LB-JAC) - WER<br/>
<b>Offensive Player</b> - Shaun Alexander (RB-SEA) - WER 
