Week 13 was a key week for post-season. It helped to clarify things a bit, but resolved very little. We do know who is going to be in the Toliet Bowl, we also know two of the playoff teams. But there are still four teams battling for two spots. Also, neither division has been wrapped up yet, although it will be tough for the Whiskey Tango to not win the Gold.</p>

<p>In a game where the winner would lock up a playoff spot, the Sacks on the Beach defeated the Werewolves with a 18-0 shutout. A win next week and the Sacks win their first division title since 2001. The Whiskey Tango picked up the second playoff spot, and most likely a division championship, by defeating the Rednecks 2-0. This also secures the Toliet Bowl slot for the Rednecks. The Whiskey Tango now have 98 all-time franchise victories.</p>

<p>The Bug Stompers put themselves on the verge of the playoffs by beating the Crusaders, 28-11. A win or tie next week and the Bug Stompers will be division champs. The Crusaders were eliminated from the division title, but remain alive for the playoffs.</p>

<p>In other games, the MeggaMen defeated the Gallic Warriors, 40-15. Keeping them in the playoff hunt and with still a long-shot at winning the division. The Norsemen ensured that the Lindbergh Baby Casserole would be going to their first franchise Toliet Bowl. In addition the LBC need to win next week to avoid finishing with the worst record in league history.</p>

<p><b>Player of the Week</b> - Hines Ward (WR-PIT) - GW<br/>
<b>Defensive Player</b> - Charles Tillman (DB-CHI) - WER
