<b>TOILET BOWL VII</b>: In their first Toilet Bowl appearance, the Lindbergh Baby Casserole managed to do what they could only do twice all season. That is win the game. They did so by defeating the Rednecks for the seventh time in eight meetings. In three appearances this marks the Rednecks first Toilet Bowl loss.</p>


<p><b>PLAYOFF GAMES</b>: The Whiskey Tango took a big lead on Saturday with Tiki Barber (RB-NYG) and game MVP Tom Brady (QB-NE). The Werewolves spent most of Sunday trying to catch up. Tied going into the Sunday night game, the Werewolves only netted 3 points with 4 players. Three points that the Whiskey Tango easily picked up with Nick Collins (DB-GB) on Monday Night. Giving the Whiskey Tango a 57-48 victory. This ends the Whiskey Tango's 2 game post-season losing streak (both Toilet Bowls) and sends them to their first championship game since 1995.</p>

<p>The other playoff game proved to be just as close and just as dramatic. With scores that flip-flopped all week, the Sacks on the Beach managed to take a 20-18 lead into Sunday night. Led by Rod Coleman (DL-ATL) and Keith Brooking (LB-ATL) the MeggaMen managed to surge ahead, 20-9. This left the Sacks hoping Samkon Gado (RB-GB) could make up the difference on Monday night. It wasn't to be, as Gado got shutout. This sends the MeggaMen to thier third Championship game and second in a row. It also leaves the Sacks on the Beach with the worst playoff record in the league (1-3). Game MVP: Jason Taylor (DL-MIA).</p>

<p><b>AWARD NOMINEES</b>: The nominations are in and it is time to vote of the awards. Please get you votes to me by Tuesday night. Thanks.</p>

<p><b>Best Defensive Player</b>
<ul><li>Keith Bulluck (LB-TEN) - CRU</li>
<li>Charles Tillman (DB-CHI) - WER</li>
<li>Adrian Wilson (DB-ARI) - WT</li>
</ul>

<b>Most Valuable Player</b>
<ul><li>Shaun Alexander (RB-SEA) - WER</li>
<li>Steve Smith (WR-CAR) - CRU</li>
<li>Ladainian Tomlinson (RB-SD) - SOB</li></ul>

<b>Bonehead Award</b>
<ul><li>Bug Stompers - Drafting Nate Burleson 2nd overall, and WRs with first 4 picks</li>
<li>Werewolves - Releasing Jay Feeley instead of Adam Vinatieri</li></ul>

<b>Best Ownership Move</b>
<ul><li>Sacks on the Beach - Picking up Samkon Gado</li>
<li>Werewolves - Trading for Rudi Johnson and Alge Crumpler in week 13</li></ul>

<b>Owner of the Year</b>
<ul><li>Tom Marsh - MeggaMen (Late season resurgence to go to back-to-back Championships)</li>
<li>Ayrik Moran - Bug Stompers (Great First year performance)</li>
<li>Josh Utterback - Werewolves (Amassing most points scored in league history) </li></ul>
