The lasst minute schedule change, due to the Hurricane, led to a plethora of bye week activations. The Bug Stompers, Lindbergh Baby Casserole, Gallic Warriors and Crusaders all got hit. They each get penalized 2 points and $1.</p>

<p>The Norsemen hope for a turn around similar to last season, as they pick up their 2nd straight win, defeating the Sacks on the Beach, 18-10. This is the third straight time the Norsemen have defeated the Sacks. No ground is lost for the Sacks however, as the Werewolves also fall, to the Gallic Warriors 39-4.</p>

<p>The Bug Stompers find themselves right back in the playoff race, by defeating the Lindbergh Baby Casserole 21-5. This marks the first time this franchise has completed a season sweep of the LBC. It is also a franchise tying 4th straight loss for the LBC, a mark they have reached 3 other times, including earlier this season.</p>

<p>The Crusaders celebrated their 200th franchise game, but lost to nemisis MeggaMen, 43-33. The Crusaders have only defeated the MeggaMen once in their last seven meetings. That allowed the Whiskey Tango to regain a share of the division lead by defeating the Rednecks, 45-16. Warren is now 3-1-1 all-time against his old team.</p>

<p><b>Player of the Week</b> - Lamont Jordan (RB-OAK) - GW<br/>
<b>Defensive Player</b> - Chris Hope (DB-PIT) - NOR
