The first bye week activations of the season occured this week.  The Whiskey
Tango, Bug Stompers and Gallic Warriors all got a 2 point penalty and a $1
fine for their illegal activations.</p>

<p>In spite of the penalties, the Whiskey Tango managed to scrap out a 24-14 
victory over the struggling Norsemen.  The Gallic Warriors also picked up a
solid 60-38 win over the Rednecks. </p>

<p>In an effort to stay even with the Whiskey Tango, the Crusaders had to play
the Sacks on the Beach, for the the 3rd time in the their last 6 games.  The
Crusaders once again came out on top, this time by a 4 point margin (28-24).
Both of the Sacks' two losses this season came at the hands of the Crusaders.</p>

<p>With the Sacks lose the door was open for the Werewolves to take sole
possession of first place.  Which they did with a 47-0 stomping of the Bug
Stompers.</p>

<p>The MeggaMen took another step toward getting back into contention with a
41-3 victory over the LBC.  This sets up this weeks battle between the LBC
and the Norsemen for the inside track to the Toliet Bowl.</p>

<p><b>Player of the Week</b> - Steve Smith (WR-CAR) - CRU<br/>
<b>Defensive Player</b> - Mike Brown (DB-CHI) - MM

