During the Monday Night double header the Whiskey Tango scored 32 points to
squeak out a victory vs the Gallic Warriors, 20-16.  Avenging their loss in 
week 14 last season, eliminating them from the playoffs.</p>

<p>The Werewolves also advanced to 2-0, with a crushing 53-0 defeat of the defending
champion MeggaMen.  This is 4th straight meeting that the Werewolves have won, 
after having lost the first 3 meetings of these teams.  It also marks the 100th
regular season win for the Werewolves.</p>

<p>Also picking up thier 100th regular season win were the Crusaders.  They defeated
the Norsemen, 13-4.  The Crusaders and the Werewolves meet next week in a battle
of 2-0 teams.</p>

<p>In the game dubbed by Warren as the Brother-in-Law Bowl, the Bug Stompers
stomp the Lindbergh Baby Casserole.  The LBC barely avoided a second straight
shutout, falling 56-1.  This marks Ayrik's first win the the WMFFL.  It is also
the 4th straight loss by the LBC, tying a franchise record.</p>

<p>In the final game, the Sacks on the Beach dominated the Gold Division Champion
Rednecks.  Winning 50-0.</p>

<p align="center">
<b>Player of the Week</b> - Donovan McNabb (QB-PHI) - BS<br/>
<b>Defensive Player</b> - Leonard Little (DL-STL) - WER<br/>
