In the battle for first in the Burgandy Division, the Sacks on the Beach defeated the Werewolves, 34-2. This game was the Werewolves' 200th franchise game. Their loss forced a tie atop the division. With the Bug Stompers 40-15 victory over the Gallic Warriors, they make it a three way tie.</p>

<p>In the other division, the MeggaMen defeated the Whiskey Tango, 38-26. Making it five teams tied for wild card spots at 5-3. The Crusaders take a step above that tie, at 6-2, with their 74-11 victory over the Lindberg Baby Casserole. The gives the LBC a franchise record 5 game losing streak. It also leaves them waiting another week for their 100th win, they are currently at 99.</p>

<p>Finally, the Rednecks had an illegal activation and the Norsemen activated a player on a bye. They each get $1 fine and 2 point penalty. Since they played each other the penalties offset. The Rednecks go on to shutout the Norsemen, 26-0, ending thier 6 game losing streak. Both Redneck wins this year have been shutouts.</p>

<p><b>Player of the Week</b> - Jake Plummer (QB-DEN) - RED<br/>
<b>Defensive Player</b> - Bert Berry (DL-ARI) - GW
