The regular season ended dramaticlly with playoff teams not being determined until Monday night. In the battle for the Burgandy Division, the Sacks on the Beach ended a 6 game losing streak to the Bug Stompers, to win thier 2nd division title in the franchise's 6 year history. They become the second team to lose the Toliet Bowl one year and win the division the following. This left the Bug Stompers needing help to make the playoffs, help that would not come.</p>

<p>In the Gold Division the Whiskey Tango wanted to win to avoid a point differential battle. But they and the Crusaders end up splitting the season series for the 5th straight year, Crusaders win 59-44. Even after the win the Crusaders needed the MeggaMen to lose. They didn't. But their margin of victory vs the Rednecks was not enough to take the division away from the Whiskey Tango. Their 52-38 victory was enough to earn a playoff berth, making it the first time since 2000 that a defending champion has made the playoffs.</p>

<p>To round out the playoff field, the Werewolves completed a season shutout sweep of the Norsemen, 29-0. Marking the fifth time in six meetings the Werewolves have won this game. The Werewolves finish with a league record 1,569 points scored this season.</p>

<p>In the final game, the Gallic Warriors defeated the Lindbergh Baby Casserole, 59-0. The LBC end the season with the worst record in league history.</p>

<p>The nominating period for the owner awards is now open.  Nominations will be taken until Tuesday night.  The awards are Bonehead Award, Best Ownership Move and Owner of the Year</p>

<p><b>Player of the Week</b> - Antonio Gates (TE-SD) - MM<br/>
<b>Defensive Player</b> - Charles Tillman (DB-CHI) - WER</p>

<p><b>Playoff Seeding</b>
<blockquote>#1 Sacks on the Beach vs #4 MeggaMen<br/>
#2 Whiskey Tango vs #3 Werewolves </blockquote>

