Lindbergh Baby Casserole activated a player not on thier roster, the Whiskey Tango activated a player on a bye.  Both get penalize 2 points and $1.</P>

<p>The playoff race intensifed as five of the six teams in playoff contention won.  The Sacks on the Beach defeated the Whiskey Tango, 28-22.  Leaving the Whiskey Tango a game behind the rest of the field at 5-4.</p>

<p>The Werewolves escaped a near loss, edging out the Lindbergh Baby Casserole on Monday night, with a 18-7 win.  This is the LBCs 6th straight loss and the Werewolves first season sweep over them in seven years.</p>

<p>The Bug Stompers kept pace with a 54-21 win against the Norsemen.  The Norsemen were playing their 200th franchise game.  In another milestone game, the Crusaders kept the best record in the league, by defeating the Rednecks, 58-10.  This marks the Rednecks 100th franchise loss.  In the final game, the MeggaMen beat the Gallic Warriors, 53-15, to tie their all-time series 5-5-1.</p>

<p><b>Player of the Week</b> - Ladainian Tomlinson (RB-SD) - SOB<br/>
<b>Defensive Player</b> - Keith Bulluck (LB-TEN) - CRU
