The MeggaMen win thier second straight Championship with a 29-0 blanking of the Whiskey Tango.  They become only the third team to win back-to-back titles (Barbarians ('93, '94, '95) and Norsemen ('99, '00)).  It is also the third time the Championship has ended in a shutout.  Clinton Portis (RB-WAS) was named the MVP of the game.</p>

<p><b>LEAGUE AWARDS</b><br/>
<b>Best Defensive Player</b> - Charles Tillman (DB-CHI) - Werewolves<br/>
<b>MVP</b> - Shaun Alexander (RB-SEA) - Werewolves<br/>
<b>Bonehead Award</b> - Ayrik Moran - Bug Stompers</br>
<b>Best Ownership Move</b> - Josh Utterback - Werewovles</br>
<b>Owner of the Year</b> - Ayrik Moran - Bug Stompers</br>
